# SwiftLint configuration for cdv2spm project

# Paths to include during linting. `--path` is ignored if present.
included:
  - Sources
  - Tests

# Paths to ignore during linting. Takes precedence over `included`.
excluded:
  - .build
  - .swiftpm
  - dist
  - Package.resolved

# Rules configuration
opt_in_rules:
  - empty_count
  - trailing_newline
  - colon
  - comma

disabled_rules:
  - trailing_whitespace

# Rule configurations
line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 500
  error: 800

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
